# Toml general config

# Paths to add
[path]
path = "~/.userseeddotfiles/bin"

# Vars to add
[vars]
EDITOR = "vi"

# Aliases to add
[alias]
seedd="echo A dot, a seed, an idea, little things that could create a new world "
